FROM golang

RUN mkdir -p $GOPATH/src/github.com/fsn-dev
RUN cd $GOPATH/src/github.com/fsn-dev
RUN git clone https://github.com/fsn-dev/dcrm-walletService.git
RUN cd dcrm-walletService && make
WORKDIR /go/dcrm-walletService
